version: "3.8"

services:
  spider:
    image: spider:dev
    container_name: spider
    hostname: spider
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - $PWD:/app
    tty: true
    networks:
      - default

networks:
  default:
    driver: bridge
