version: "3.7"

services:
  spider:
    image: spider:dev
    container_name: spider
    hostname: spider
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - $PWD:/app/spider
    tty: true
