version: "3.8"

services:
  spider:
    image: spider:release
    container_name: spider
    hostname: spider
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - $PWD/config.yaml:/app/etc/config.yaml:ro
      - $PWD/data:/app/data
    tty: true
    networks:
      - default

networks:
  default:
    driver: bridge
