{{- $fullname := include "spider-cplusplus.fullname" . }}
{{- $releaseNamespace := include "spider-cplusplus.namespace" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spider-cplusplus.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    entry: {{ .Values.config.spider.entry | quote }}
    useragent: {{ .Values.config.spider.useragent | quote }}
    timezone: {{ .Values.config.spider.timezone | quote }}
    token:
{{ toYaml .Values.config.spider.token | indent 6 }}
    sleep: {{ int .Values.config.spider.sleep }}
    crawler:
{{ toYaml .Values.config.crawler | indent 6 }}
    database:
      type: {{ .Values.config.database.type | quote }}
      mongodb:
      {{- if .Values.externalDatabase.enabled }}
        dsn: {{ .Values.externalDatabase.mongodb.dsn | quote }}
      {{- else }}
        dsn: mongodb://{{ .Values.mongodb.auth.username }}:{{ .Values.mongodb.auth.password }}@{{ printf "%s-mongodb" $fullname }}.{{ $releaseNamespace }}.svc.{{ .Values.clusterDomain }}:{{ .Values.mongodb.service.port }}/{{ .Values.mongodb.auth.database }}
      {{- end }}
