apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spider-cplusplus.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
{{ toYaml .Values.spider | indent 4 }}
