style: github
template: CHANGELOG.tpl
info:
  title: CHANGELOG
  repository_url: https://github.com/spider-all/spider-cplusplus
options:
  commits:
    filters:
      Type:
        - sparkles
        - bug
        - zap
        - recycle
        - fire
        - truck
        - bookmark
        - heavy_plus_sign
        - heavy_minus_sign
        - arrow_down
        - arrow_up
  commit_groups:
    title_maps:
      sparkles: Features
      bug: Bug Fixes
      zap: Performance Improvements
      recycle: Code Refactoring
      fire: Remove files
      truck: Rename files
      bookmark: Release version
      heavy_plus_sign: Dependencies
      heavy_minus_sign: Dependencies
      arrow_down: Dependencies
      arrow_up: Dependencies
    group_by: Type
  header:
    pattern: "^:(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
