style: github
template: CHANGELOG.tpl
info:
  title: CHANGELOG
  repository_url: https://github.com/spider-all/spider-cplusplus
options:
  commits:
    filters:
      Type:
        - sparkles
        - bug
        - zap
        - recycle
        - fire
        - truck
        - bookmark
  commit_groups:
    title_maps:
      sparkles: Features
      bug: Bug Fixes
      zap: Performance Improvements
      recycle: Code Refactoring
      fire: Remove files
      truck: Rename files
      bookmark: Release version
    group_by: Type
  header:
    pattern: "^:(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
