name: Image CI

on:
  push:
    branches:
      - main
      - dev
    tags:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  image:
    name: Image builder
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: tosone
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Compile docker image
        run: |
          docker build -t ghcr.io/spider-all/spider-cplusplus:$GITHUB_SHA .
