name: Image CI

on:
  push:
    branches:
      - main
      - test
      - dev
  pull_request:
    branches:
      - main

jobs:
  image:
    name: Image builder
    runs-on: ubuntu-20.04

    steps:
      - name: Print Title of PR
        run: echo The Title of your PR is ${{ github.event.pull_request.title }}
      - name: Print Body of PR
        run: |
          if [[ "${{ github.event.pull_request.title }}" =~ ^:heavy_plus_sign:.*|^:arrow_up: ]]; then
            echo "yes1"
          fi
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: tosone
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set env
        id: vars
        run: |
          echo "::set-output name=date::$(date +'%Y%m%d%H%M')"
          echo "::set-output name=tag::$(jq --raw-output '.version' package.json | tr -d '')"
      - name: Compile docker image
        run: |
          docker build --build-arg SPIDER_VERSION=${{ steps.vars.outputs.tag }} -t ghcr.io/spider-all/spider-cplusplus:${{ steps.vars.outputs.tag }}-${{ steps.vars.outputs.date }} .
          docker push ghcr.io/spider-all/spider-cplusplus:${{ steps.vars.outputs.tag }}-${{ steps.vars.outputs.date }}
