name: Image CI

on:
  push:
    branches:
      - main
      - dev
    tags:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  image:
    name: Image builder
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Compile docker image
        run: make image
  build:
    name: Native builder
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install packages
        run: sudo apt-get install ccache
      - name: Install deps
        run: |
          export DEPS=$(jq --raw-output '.dependencies | keys | join(" ")' package.json| tr -d "")
          vcpkg install ${DEPS}
          vcpkg export ${DEPS} --raw --output=pkgs --output-dir=.
      - name: Compile
        run: make debug release
