name: Image CI

on:
  push:
    branches:
      - main
      - dev
    tags:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  image:
    name: Image builder
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: tosone
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Compile docker image
        run: |
          docker build -t ghcr.io/spider-all/spider-cplusplus:$GITHUB_SHA .
  build:
    name: Native builder
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install packages
        run: sudo apt-get install ccache libsasl2-dev
      - name: Install deps
        run: make deps
      - name: Compile
        run: make debug release
