name: Build dependencies

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "dependency image tag"
        type: string
        required: true
      vcpkg_tool_version:
        description: "vcpkg tool version"
        type: string
        default: "2024-10-18"
        required: false
      vcpkg_version:
        description: "vcpkg version"
        type: string
        default: "2024.10.21"
        required: false
jobs:
  build-dependency-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: tosone
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ inputs.tag }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/base.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: false
          sbom: false
          outputs: oci-mediatypes=true,force-compression=true,type=image
          build-args: |
            VCPKG_TOOL_VERSION=${{ inputs.vcpkg_tool_version }}
            VCPKG_VERSION=${{ inputs.vcpkg_version }}
