name: Pull Request CI

on: [pull_request]

jobs:
  image:
    name: Image builder
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: tosone
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set env
        id: vars
        run: |
          echo "::set-output name=date::$(date +'%Y%m%d%H%M')"
          echo "::set-output name=tag::$(cat VERSION | tr -d '')"
      - name: Compile base docker image
        run: |
          if [[ "${{ github.event.pull_request.title }}" =~ ^:heavy_plus_sign:.*|^:arrow_up:.*|^:heavy_minus_sign:.*|^:arrow_down:.* ]]; then
            docker build -t ghcr.io/spider-all/spider-cplusplus:${{ steps.vars.outputs.tag }}-base -f Dockerfile.base .
            docker push ghcr.io/spider-all/spider-cplusplus:${{ steps.vars.outputs.tag }}-base
          fi
      - name: Compile docker image
        run: |
          docker build --build-arg SPIDER_VERSION=${{ steps.vars.outputs.tag }} -t ghcr.io/spider-all/spider-cplusplus:${{ steps.vars.outputs.tag }}-${{ steps.vars.outputs.date }} .
          docker push ghcr.io/spider-all/spider-cplusplus:${{ steps.vars.outputs.tag }}-${{ steps.vars.outputs.date }}
