on:
  push:
    tags:
      - "v*"

name: Create Release

jobs:
  image:
    name: Image builder
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set env
        run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: tosone
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Compile docker image
        run: |
          docker build -t ghcr.io/spider-all/spider-cplusplus:base-${{ env.GIT_TAG }} -f Dockerfile.base .
          docker push ghcr.io/spider-all/spider-cplusplus:base-${{ env.GIT_TAG }}
          docker build -t ghcr.io/spider-all/spider-cplusplus:${{ env.GIT_TAG }} -f Dockerfile .
          docker push ghcr.io/spider-all/spider-cplusplus:${{ env.GIT_TAG }}
